[package]
name = "lite-rpc"
version = "0.1.0"
edition = "2021"
description = "A lite version of solana rpc to send and confirm transactions"

[workspace]
members = [
    "bench"
]

[workspace.dependencies]
tokio = { version = "1.25.0", features = ["full"]}
solana-sdk = { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-rpc-client = { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
log = "0.4.17"
clap = { version = "4.2.1", features = ["derive"] }
anyhow = "1.0.70"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tracing-subscriber = "0.3.16"

[dev-dependencies]
bench = { path = "./bench" }

[dependencies]
solana-rpc-client-api= { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-tpu-client= { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-quic-client= { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-pubsub-client= { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-transaction-status = { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-version= { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-client= { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
bincode = "1.3.3"
bs58 = "0.4.0"
base64 = "0.21.0"
thiserror = "1.0.38"
futures = "0.3.26"
bytes = "1.4.0"
dashmap = "5.4.0"
const_env = "0.1.2"
jsonrpsee = { version = "0.16.2", features = ["macros", "full"] }
tokio-postgres = "0.7.7"
native-tls = "0.2.11"
postgres-native-tls = "0.5.0"
prometheus = "0.13.3"
lazy_static = "1.4.0"
dotenv = "0.15.0"
async-channel = "1.8.0"
tokio = { workspace = true, features = ["fs"] }
clap = { workspace = true }
solana-sdk = { workspace = true }
solana-rpc-client = { workspace = true } 
log = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing-subscriber = { workspace = true }
