[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["fs"] }
clap = { workspace = true }
solana-sdk = { workspace = true }
solana-rpc-client = { workspace = true } 
log = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing-subscriber = { workspace = true }
csv = "1.2.1"
dirs = "5.0.0"
rand = "0.8.5"

