app = "solana-lite-rpc"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "../Dockerfile"

[experimental]
  cmd = ["lite-rpc", "--rpc-addr", "$RPC_URL", "--ws-addr", "$WS_URL"]

[env]
  PORT_HTTP = "8890"
  PORT_WS = "8891"
  RUST_LOG = "info"

[[services]]
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1024
    soft_limit = 1024
    type = "connections"

[[services]]
  internal_port = 9001
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1024
    soft_limit = 1024
    type = "connections"

 [metrics]
   path = "/metrics"
   port = 9091
